# Generated by Django 3.1.12 on 2024-11-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSAKey',
        ),
    ]
